-- supabase_schema.sql (vereinfachtes Schema)
create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now()
);

create table if not exists areas (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete cascade,
  name text not null,
  color text,
  created_at timestamp with time zone default now()
);

create table if not exists users_incanto (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null check (role in ('putzkraft','personal','geschaeft')),
  email text unique,
  created_at timestamp with time zone default now()
);

create table if not exists work_orders (
  id bigint generated by default as identity primary key,
  area_id bigint references areas(id) on delete set null,
  title text not null,
  assigned_to bigint references users_incanto(id) on delete set null,
  start_plan timestamp with time zone,
  end_plan timestamp with time zone,
  address text, lat double precision, lon double precision,
  instructions text,
  status text,
  approved boolean default false,
  published boolean default false,
  updated_at timestamp with time zone default now()
);

create table if not exists time_entries (
  id bigint generated by default as identity primary key,
  user_id bigint references users_incanto(id) on delete set null,
  area_id bigint references areas(id) on delete set null,
  work_order_id bigint references work_orders(id) on delete set null,
  start_ts timestamp with time zone not null,
  end_ts timestamp with time zone not null,
  duration_min integer not null,
  note text,
  geo_start_lat double precision, geo_start_lon double precision,
  geo_end_lat double precision, geo_end_lon double precision,
  approved boolean default false,
  published boolean default false,
  updated_at timestamp with time zone default now()
);

create table if not exists portal_tokens (
  id bigint generated by default as identity primary key,
  client_id bigint references clients(id) on delete cascade,
  token text unique not null,
  active boolean default true,
  valid_from date, valid_to date,
  created_at timestamp with time zone default now()
);

-- Views for portal
create or replace view time_entries_view as
select te.*, u.name as user_name, a.name as area_name
from time_entries te
left join users_incanto u on u.id = te.user_id
left join areas a on a.id = te.area_id;

create or replace view work_orders_view as
select wo.*, au.name as assigned_name, a.name as area_name
from work_orders wo
left join users_incanto au on au.id = wo.assigned_to
left join areas a on a.id = wo.area_id;
